### PR TITLE
New dynamic filters for explore and collections

### PR DESCRIPTION
**Pull request by antho1404**
### Description

Redesign of the filter for the explore page and the collection page.
This filter includes the filter of type of offer, price, collections, and collection traits.

This PR focuses only on adding the feature for filter but not the design

### CODE REVIEW

**Comment by EmmanuelDrouin** [comment]
[Collection work - Update filters component](https://trello.com/c/OhMsClLf/429-collection-work-update-filters-component)

**Comment by antho1404** [comment]
@EmmanuelDrouin I would love to have your feedback on that already, just focussing on the UX part and not the UI yet

**Comment by EmmanuelDrouin** [comment]
> @EmmanuelDrouin I would love to have your feedback on that already, just focussing on the UX part and not the UI yet

My UX feedback:

### Filters on explore page

- The "collections" section in the filters should be open by default when you land on the page (like other platforms)
  - Screen Shot 2566-01-31 at 12 48 32
- The filter by "type" is missing (all, single edition, multiple editions)
- We have a bug with the "currency selector" in the "price range", on click it opens the dropdown menu, but then the selector disappears
  - https://user-images.githubusercontent.com/15095289/215677284-0fec8436-4767-4a50-b4c9-4ae33334ecce.mov
- Categories
  - Categories displayed have a weird naming with numbers displayed at the end
    - Screen Shot 2566-01-31 at 12 56 37
  - The number of traits available in a property is not displayed next to the property title (EG: category = 4)
    - Screen Shot 2566-01-31 at 12 58 29
  - I think as we are displaying these like any traits, we should use the same format and in this case display like on the Figma design:
    - Total count of traits inside each section
    - Total count of assets that have the same trait (on the trait itself)
    - Percentage  display bellow based on that data (x% have this trait)
- Once a collection is selected, then the section "collections" section is renamed "Collection & properties"
  - The search to filter properties is missing
  - Design file > [Collection selected](https://www.figma.com/file/0AHxoPROqyuCllH6JqArVQ/Marketplace-Template---UI-Flows?node-id=1256%3A135882&t=MyW3vKaIY87v7hyD-4) 

### Filters on collection page
- Missing "properties" section with search to filter properties
- The properties section with the first property should be open by default when a user land on the page
  - Design file > [filters on collection page ](https://www.figma.com/file/0AHxoPROqyuCllH6JqArVQ/Marketplace-Template---UI-Flows?node-id=1113%3A147004&t=MyW3vKaIY87v7hyD-4)
- On the collection page, the pagination is not properly included in the assets grid section but instead applyed to the all page
  - Screen Shot 2566-01-31 at 13 07 18
  - Screen Shot 2566-01-31 at 13 07 22

### Responsive
Todo with Ismail

**Comment by antho1404** [comment]
> The "collections" section in the filters should be open by default when you land on the page (like other platforms)
Done

> The filter by "type" is missing (all, single edition, multiple editions)
Discussion opened on Figma, we discussed something different over our previous call

> We have a bug with the "currency selector" in the "price range", on click it opens the dropdown menu, but then the selector disappears
Yes that needs "design" fix

> Categories
Design related (not done yet) and not needed as a section (discussion on figma)

> Once a collection is selected, then the section "collections" section is renamed "Collection & properties"
Done even tho the translation needs to be done properly

> Missing "properties" section with search to filter properties
Done

> The properties section with the first property should be open by default when a user land on the page
Done

> On the collection page, the pagination is not properly included in the assets grid section but instead applyed to the all page
Fixed

**Comment by EmmanuelDrouin** [comment]
Dedicated issue to finalize the UI work created > https://github.com/liteflow-labs/starter-kit/issues/155

**Comment by antho1404** [comment]
closing to focus the review process exclusively on https://github.com/liteflow-labs/starter-kit/pull/158 that includes this already

**Pull request closed without merging**
