### PR TITLE
Add collection name to the Token page header + Refresh metadata functionality

### PR DESCRIPTION
**Pull request by achampagnedev**
### Project organization

- Trello card: https://trello.com/c/xIgYx9xZ
- Trello card: https://trello.com/c/FV5FMleK

### Description

- Added collection name on the home page featured Token
- Added collection name on the detail page of a Token
- Added the "Refresh Metadata" button and functionality to the detail page of a Token (in the ... menu)

### How to test

Check if the collection name appears on the Home page + Detail page
Check if the metadata refresh successfully

### CODE REVIEW

**Comment by antho1404** [comment]
The build is broken and preview not deployed, could you fix that before I review

**Comment by antho1404** [comment]
Do not merge until the collection page is created as it adds links to the collection page

**Comment by EmmanuelDrouin** [comment]
[Collection - Update Token card header component UI](https://trello.com/c/xIgYx9xZ/432-collection-update-token-card-header-component-ui)

**Comment by EmmanuelDrouin** [comment]
@achampagnedev one feedback, please place the "report" bellow the "refresh metadata" in the dropdown menu of the ellipsis, we don't want the first action a user will see to be the report (this will be the last one if we add more functionality in the dropdown)

Screen Shot 2566-01-18 at 14 53 28

**Comment by achampagnedev** [comment]
@EmmanuelDrouin Swapped the choices.

**Review by antho1404 — APPROVED** [review]

**Pull request merged**
